name: AWS Instance Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run command on AWS instance
        run: |
          ssh Github_user@54.87.160.87 'echo "Hello from GitHub Workflow"'

